#!/bin/bash

# Alisa Installer
#
# Copyright (c) 2023, Radio New Japan.
#
# Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions  are met:
# 1. Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
# 3. Neither the name of the copyright holder nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS “AS IS” AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
# IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

VERSION="0.1"
DISTRONAME="Alisa Linux"
APPTITLE="${DISTRONAME} Installer ${VERSION}"

_setlocale(){
	langs="$(ls /usr/share/i18n/locales | sed -z "s/\n/,/g")"
	opts=()
	IFSOLD=$IFS
	IFS=,
	for lang in ${langs[@]}; do
		opts+=("${lang}" "" "OFF")
	done
	IFS=$IFSOLD
	locale="$(whiptail --backtitle "${APPTITLE}" \
			   --checklist "Select locale(s)" 25 50 14 \
			   "${opts[@]}" 3>&1 1>&2 2>&3)"
	return 0
}

_setkeymap(){
	keys="$(localectl list-keymaps | sed -z "s/\n/,/g")"
	opts=()
	IFSOLD=$IFS
	IFS=,
	for key in ${keys[@]}; do
		opts+=("${key}" "")
	done
	IFS=$IFSOLD
	keymap="$(whiptail --backtitle "${APPTITLE}" \
			   --menu "Select a keymap" 25 50 14 \
			   "${opts[@]}" 3>&1 1>&2 2>&3)"
	#loadkeys "${keymap}"
	return 0
}

_network(){
	whiptail --backtitle "${APPTITLE}" \
		 --yesno "Configure network?" 0 0 0
	if [ "$?" = "1" ]; then
		return 0
	else
		 nmtui
		return 0
	fi
}

_timezone(){
	regions=(
		"Africa" "America" "Atlantica" "Arctic" "Asia" "Atlantic" 
		"Australia" "Brazil" "Canada" "Chile" "Europe" "Indian" 
		"Mexico" "Pacific" "US"
	)
	opts=()
	for region in "${regions[@]}"; do
		opts+=("${region}" "")
	done
	timezone="$(whiptail --backtitle "${APPTITLE}" \
			     --menu "Select A Timezone" 25 50 14 \
			     "${opts[@]}" 3>&1 1>&2 2>&3)"
	
	cities="$(ls /usr/share/zoneinfo/${timezone} | sed -z "s/\n/,/g")"
	opts=()
	IFSOLD=$IFS
	IFS=,
	for city in ${cities[@]}; do
		opts+=("${city}" "")
	done
	IFS=$IFSOLD
	timezone="${timezone}/$(whiptail --backtitle "${APPTITLE}" \
			   --menu "Select locale(s)" 25 50 14 \
			   "${opts[@]}" 3>&1 1>&2 2>&3)"

	timezone="/usr/share/zoneinfo/"${timezone}""
	return 0
}

_diskpart(){
	devs=$(lsblk -dpnl -o NAME,SIZE)
	opts=()
	IFSOLD=$IFS
	IFS=$'\n'
	for dev in ${devs}; do
		opts+=("${dev}" "")
	done
	IFS=$IFSOLD
	device=$(whiptail --backtitle "${APPTITLE}" \
			  --menu "Select a drive" 0 0 0 \
			  "${opts[@]}" 3>&1 1>&2 2>&3)
	if [ "$?" != "0" ]; then
		return 1
	fi
	echo ${dev%%\ *}
	#cgdisk ${dev}
	return 0
}

whiptail --yesno "Welcome to Alisa Linux installer! \n\n Select 'Continue' to install this OS, or 'Cancel' not to do." 20 50 10
if [ "$?" = "1" ]; then
	exit 1
fi
_setlocale
_setkeymap
_network
_timezone
_diskpart

