#!/bin/bash

# Alisa Installer
#
# Copyright (c) 2023, Radio New Japan.
#
# Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions  are met:
# 1. Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
# 3. Neither the name of the copyright holder nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS “AS IS” AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
# IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

VERSION="0.1"
DISTRONAME="Alisa Linux"
APPTITLE="${DISTRONAME} Installer ${VERSION}"

_setlocale(){
	langs="$(ls /usr/share/i18n/locales | sed -z "s/\n/,/g")"
	opts=()
	IFSOLD=$IFS
	IFS=,
	for lang in ${langs[@]}; do
		opts+=("${lang}" "" "OFF")
	done
	IFS=$IFSOLD
	locale="$(whiptail --backtitle "${APPTITLE}" \
			   --title "Language Support" \
			   --checklist "" 25 50 14 \
			   "${opts[@]}" 3>&1 1>&2 2>&3)"
	return 0
}

_setkeymap(){
	keys="$(localectl list-keymaps | sed -z "s/\n/,/g")"
	opts=()
	IFSOLD=$IFS
	IFS=,
	for key in ${keys[@]}; do
		opts+=("${key}" "")
	done
	IFS=$IFSOLD
	keymap="$(whiptail --backtitle "${APPTITLE}" \
			   --title "Keyboard" \
			   --menu "" 25 50 14 \
			   "${opts[@]}" 3>&1 1>&2 2>&3)"
	#loadkeys "${keymap}"
	return 0
}

_netconn(){
	whiptail --backtitle "${APPTITLE}" \
		 --yesno "Configure network connection?" 0 0 0
	if [ "$?" = "1" ]; then
		:
	else
		 nmtui
	fi
}

_hostname(){
	hostname="$(whiptail --title "Host name" \
			     --inputbox "This is the name of your computer on the network. It can't start or end with a hyphen." \
			     10 50 alisalinux 3>&1 1>&2 2>&3)"
	echo "${hostname}" | grep -e '^-' -e '-$'
	if [ "$?" = "0" ]; then
		whiptail --title "Host name" \
			 --msgbox "Don't start or end with a hyphen!" 0 0
		_hostname
	fi
	return 0
}

_timezone(){
	regions=(
		"Africa" "America" "Atlantica" "Arctic" "Asia" "Atlantic" 
		"Australia" "Brazil" "Canada" "Chile" "Europe" "Indian" 
		"Mexico" "Pacific" "US"
	)
	opts=()
	for region in "${regions[@]}"; do
		opts+=("${region}" "")
	done
	timezone="$(whiptail --backtitle "${APPTITLE}" \
			     --title "Timezone" \
			     --menu "" 25 50 14 \
			     "${opts[@]}" 3>&1 1>&2 2>&3)"
	
	cities="$(ls /usr/share/zoneinfo/${timezone} | sed -z "s/\n/,/g")"
	opts=()
	IFSOLD=$IFS
	IFS=,
	for city in ${cities[@]}; do
		opts+=("${city}" "")
	done
	IFS=$IFSOLD
	timezone="${timezone}/$(whiptail --backtitle "${APPTITLE}" \
			   --title "Timezone" \
			   --menu "" 25 50 14 \
			   "${opts[@]}" 3>&1 1>&2 2>&3)"

	timezone="/usr/share/zoneinfo/"${timezone}""
	return 0
}

_diskpart(){
	drvs=$(lsblk -dpnl -o NAME,SIZE)
	opts=()
	IFSOLD=$IFS
	IFS=$'\n'
	for drv in ${drvs}; do
		opts+=("${dev}" "")
	done
	IFS=$IFSOLD
	drive=$(whiptail --backtitle "${APPTITLE}" \
			  --title "Installation Destinaton" \
			  --menu "" 0 0 0 \
			  "${opts[@]}" 3>&1 1>&2 2>&3)
	if [ "$?" != "0" ]; then
		return 1
	fi
	cgdisk ${drive%%\ *}
	return 0
}

_rootpass(){
	rootpassword="$(whiptail --backtitle "${APPTITLE}" \
				 --title "Root Password" \
				 --passwordbox "Set the longest possible password using a mix of upper - and lower-case alphabets, numbers, and symbols.\n" \
				 13 50 3>&1 1>&2 2>&3)"
	rootpassconfirm="$(whiptail --backtitle "${APPTITLE}" \
				    --title "Root Password" \
				    --passwordbox "Enter again for confirmation.\n" \
				    13 50 3>&1 1>&2 2>&3)"
	if [ "${rootpassword}" != "${rootpassconfirm}" ]; then
		whiptail --backtitle "${APPTITLE}" \
			 --title "Root Password" \
			 --msgbox "Passwords don't match! Please try again." 0 0
		_rootpass
	fi
	return 0
}

whiptail --backtitle "${APPTITLE}" \
	 --title "Welcome to the Alisa Linux Installer!" \
	 --yesno "Select 'Continue' to install this OS, or 'Cancel' not to do." 20 50 10
if [ "$?" = "1" ]; then
	exit 1
fi
_setlocale
_setkeymap
_netconn
_hostname
_timezone
_diskpart
_rootpass

