#!/bin/bash

# Alisa Installer
#
# Copyright (c) 2023, Radio New Japan.
#
# Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions  are met:
# 1. Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
# 3. Neither the name of the copyright holder nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS “AS IS” AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
# IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

VERSION="0.1"
DISTRONAME="Alisa Linux"
APPTITLE="${DISTRONAME} Installer ${VERSION}"

startmenu(){
	_cmds=()
	_cmds+=("setlocale" "Select Locale(s)")
	_cmds+=("setkeymap" "Select A Keymap")
	_cmds+=("networkconf" "Network Configuration")
	_cmds+=("timezone" "Timezone")
	_cmds+=("diskpart" "Installation Destination")
	_cmds+=("rootpass" "Root Password")
	_cmds+=("usercreate" "User Creation")
	_cmds+=("instprof" "Install Profile")
	_command="$(whiptail --backtitle "${APPTITLE}" \
		   --menu --notags "" 0 0 0 \
		   "${_cmds[@]}" 3>&1 1>&2 2>&3)"
	if [ "$?" = "0" ]; then
		case ${_command} in
			"setlocale")
				_setlocale
				;;
			"setkeymap")
				_setkeymap
				;;
			"networkconf")
				_network
				;;
			"timezone")
				_timezone
				;;
			"diskpart")
				_diskpart
				;;
			"rootpass")
				_rootpass
				;;
			"usercreate")
				_usercreate
				;;
			"instprof")
				_instprof
				;;
		esac
	fi
}

_setlocale(){
	langs="$(ls /usr/share/i18n/locales | sed -z "s/\n/,/g")"
	opts=()
	IFSOLD=$IFS
	IFS=,
	for lang in ${langs[@]}; do
		opts+=("${lang}" "" "OFF")
	done
	IFS=$IFSOLD
	locale="$(whiptail --backtitle "${APPTITLE}" \
			   --checklist "Select locale(s)" 0 0 0 \
			   "${opts[@]}" 3>&1 1>&2 2>&3)"
	return 0
}

_setkeymap(){
	keys="$(localectl list-keymaps | sed -z "s/\n/,/g")"
	opts=()
	IFSOLD=$IFS
	IFS=,
	for key in ${keys[@]}; do
		opts+=("${key}" "")
	done
	IFS=$IFSOLD
	echo ${opts[0]}
	keymap="$(whiptail --backtitle "${APPTITLE}" \
			   --menu "Select a keymap" 0 0 0 \
			   "${opts[@]}" 3>&1 1>&2 2>&3)"
	loadkeys "${keymap}"
	return 0
}

_network(){
	nmtui
	startmenu
}

_diskpart(){
	devs=$(lsblk -dpnl -o NAME,SIZE)
	opts=()
	IFSOLD=$IFS
	IFS=$'\n'
	for dev in ${devs}; do
		opts+=("${dev}" "")
	done
	IFS=$IFSOLD
	device=$(whiptail --backtitle "${APPTITLE}" \
			--menu "Select a drive" 0 0 0 \
			"${opts[@]}" 3>&1 1>&2 2>&3)
	if [ "$?" != "0" ]; then
		return 1
	fi
	echo ${dev%%\ *}
	startmenu
}

startmenu
